#!/usr/bin/env python3
"""Generate the on-screen keyboard font ROM and layout include for osk.sv.

  tools/gen_osk.py <font8x8_basic.h>

The font is font8x8_basic by Daniel Hepper (public domain,
https://github.com/dhepper/font8x8): 8 bytes per glyph, bit 0 = leftmost pixel.
Codes 1-4 are replaced by arrow glyphs and 5 by a pound sign. Edit LAYOUT here,
not the generated files.
"""
import re
import sys
from pathlib import Path

CORE = Path(__file__).resolve().parent.parent / "src/fpga/core"

# 5 rows x 16 cells: (label, HID usage). Labels are up to 2 characters (cells are
# 20 pixels wide); \x01-\x04 are the up/down/left/right arrows, \x05 the pound sign.
# E0/E1/E2/E5 are sticky modifiers (CTRL, SHIFT, C=, right SHIFT). The usages are
# those hid_c64.sv maps onto the C64 keys (fpga64_keyboard.vhd).
LAYOUT = [
    [("<-", 0x35), ("1", 0x1E), ("2", 0x1F), ("3", 0x20), ("4", 0x21), ("5", 0x22), ("6", 0x23), ("7", 0x24),
     ("8", 0x25), ("9", 0x26), ("0", 0x27), ("+", 0x2E), ("-", 0x2D), ("\x05", 0x31), ("HM", 0x4A), ("DL", 0x2A)],
    [("CT", 0xE0), ("Q", 0x14), ("W", 0x1A), ("E", 0x08), ("R", 0x15), ("T", 0x17), ("Y", 0x1C), ("U", 0x18),
     ("I", 0x0C), ("O", 0x12), ("P", 0x13), ("@", 0x2F), ("*", 0x30), ("^", 0x42), ("RE", 0x44), ("F1", 0x3A)],
    [("RS", 0x29), ("A", 0x04), ("S", 0x16), ("D", 0x07), ("F", 0x09), ("G", 0x0A), ("H", 0x0B), ("J", 0x0D),
     ("K", 0x0E), ("L", 0x0F), (":", 0x33), (";", 0x34), ("=", 0x43), ("RT", 0x28), ("IN", 0x49), ("F3", 0x3C)],
    [("C=", 0xE2), ("SH", 0xE1), ("Z", 0x1D), ("X", 0x1B), ("C", 0x06), ("V", 0x19), ("B", 0x05), ("N", 0x11),
     ("M", 0x10), (",", 0x36), (".", 0x37), ("/", 0x38), ("SH", 0xE5), ("\x01", 0x52), ("RT", 0x28), ("F5", 0x3E)],
    [("SL", 0x39), ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C),
     ("SP", 0x2C), ("SP", 0x2C), ("SP", 0x2C), ("\x03", 0x50), ("\x02", 0x51), ("\x04", 0x4F), ("RT", 0x28), ("F7", 0x40)],
]

GLYPHS = {
    1: [0x18, 0x3C, 0x7E, 0xFF, 0x18, 0x18, 0x18, 0x00],  # up
    2: [0x18, 0x18, 0x18, 0xFF, 0x7E, 0x3C, 0x18, 0x00],  # down
    3: [0x08, 0x0C, 0xFE, 0xFF, 0xFE, 0x0C, 0x08, 0x00],  # left  (bit 0 = left pixel)
    4: [0x10, 0x30, 0x7F, 0xFF, 0x7F, 0x30, 0x10, 0x00],  # right
    5: [0x1C, 0x22, 0x02, 0x0F, 0x02, 0x02, 0x7F, 0x00],  # pound
}


def main():
    src = Path(sys.argv[1]).read_text()
    glyphs = [[int(b, 16) for b in re.findall(r"0x([0-9A-Fa-f]{2})", row)]
              for row in re.findall(r"\{([^}]*)\}", src.split("=", 1)[1])]
    assert len(glyphs) == 128 and all(len(g) == 8 for g in glyphs)
    for code, g in GLYPHS.items():
        glyphs[code] = g
    (CORE / "osk_font.hex").write_text("".join(f"{b:02x}\n" for g in glyphs for b in g))

    lines = ["// Generated by tools/gen_osk.py - edit LAYOUT there.",
             "function automatic [7:0] osk_usage(input [2:0] row, input [3:0] col);",
             "\tcase ({row, col})"]
    for r, keys in enumerate(LAYOUT):
        assert len(keys) == 16
        for c, (_, usage) in enumerate(keys):
            lines.append(f"\t\t7'd{r * 16 + c}: osk_usage = 8'h{usage:02X};")
    lines += ["\t\tdefault: osk_usage = 8'h00;", "\tendcase", "endfunction", "",
              "// label character at (row, col, position 0-1), centred in 2 characters",
              "function automatic [6:0] osk_char(input [2:0] row, input [3:0] col, input pos);",
              "\tcase ({row, col, pos})"]
    for r, keys in enumerate(LAYOUT):
        for c, (label, _) in enumerate(keys):
            assert len(label) <= 2, label
            text = label.ljust(2)
            for p, ch in enumerate(text):
                if ch != " ":
                    lines.append(f"\t\t8'd{(r * 16 + c) * 2 + p}: osk_char = 7'd{ord(ch)};")
    lines += ["\t\tdefault: osk_char = 7'd32;", "\tendcase", "endfunction", "",
              "// one-character labels are drawn centred in the cell",
              "function automatic osk_narrow(input [2:0] row, input [3:0] col);",
              "\tcase ({row, col})"]
    for r, keys in enumerate(LAYOUT):
        for c, (label, _) in enumerate(keys):
            if len(label) == 1:
                lines.append(f"\t\t7'd{r * 16 + c}: osk_narrow = 1'b1;")
    lines += ["\t\tdefault: osk_narrow = 1'b0;", "\tendcase", "endfunction", ""]
    (CORE / "osk_layout.svh").write_text("\n".join(lines))


if __name__ == "__main__":
    main()
