//
// osk.sv - on-screen keyboard for handheld play (no Dock keyboard)
//
// osk_ctrl turns pad 1 into keyboard navigation while the keyboard is shown;
// osk_overlay draws it over the video stream going to the APF scaler.
// Layout and font are generated by tools/gen_osk.py; see docs/input.md.
//

`default_nettype none

module osk_ctrl (
	input  wire        clk,          // clk_32
	input  wire        reset,
	input  wire [15:0] pad,          // cont1_key[15:0]

	output reg         visible,
	output reg   [2:0] cur_row,
	output reg   [3:0] cur_col,
	output reg   [2:0] mods,         // latched {C=, shift, ctrl}
	output reg   [7:0] key,          // HID usage held down, 0 = none
	output reg         mouse_toggle, // Start pressed with the keyboard hidden
	output reg         select_long   // Select held ~0.6 s (instead of a short press)
);

`include "osk_layout.svh"

localparam ROWS = 5, COLS = 16;
localparam [23:0] REPEAT_FIRST = 24'd12_800_000;  // ~400 ms at 32 MHz
localparam [23:0] REPEAT_NEXT  = 24'd3_200_000;   // ~100 ms
localparam [24:0] LONG_PRESS   = 25'd19_200_000;  // ~600 ms

wire up = pad[0], down = pad[1], left = pad[2], right = pad[3];
wire btn_a = pad[4], btn_b = pad[5], select = pad[14], start = pad[15];

reg  [15:0] pad_d;
reg  [23:0] repeat_cnt;
wire [3:0]  dir = pad[3:0];
wire        dir_edge = |(pad[3:0] & ~pad_d[3:0]);
wire [7:0]  usage = osk_usage(cur_row, cur_col);
wire        usage_is_mod = usage == 8'hE0 || usage == 8'hE1 || usage == 8'hE2 || usage == 8'hE5;

initial begin
	visible = 1'b0; cur_row = 3'd0; cur_col = 4'd0; mods = 3'b000; key = 8'h00; mouse_toggle = 1'b0;
	select_long = 1'b0;
end

// Select: a short press (released before LONG_PRESS) toggles the keyboard; holding it
// pulses select_long once instead
reg [24:0] sel_time = 25'd0;
reg        sel_fired = 1'b0;

always @(posedge clk) begin
	reg step;
	pad_d <= pad;
	mouse_toggle <= 1'b0;
	select_long <= 1'b0;

	if (select) begin
		if (sel_time != LONG_PRESS) sel_time <= sel_time + 25'd1;
		else if (!sel_fired) begin sel_fired <= 1'b1; select_long <= 1'b1; end
	end else begin
		sel_time <= 25'd0;
		sel_fired <= 1'b0;
	end

	if (reset) begin
		visible <= 1'b0;
		mods <= 3'b000;
		key <= 8'h00;
	end else begin
		if (~select & pad_d[14] & ~sel_fired) begin
			visible <= ~visible;
			key <= 8'h00;
		end
		if (start & ~pad_d[15] & ~visible) mouse_toggle <= 1'b1;

		if (visible) begin
			// D-pad with auto-repeat
			step = 1'b0;
			if (dir == 4'd0) repeat_cnt <= 24'd0;
			else if (dir_edge) begin step = 1'b1; repeat_cnt <= REPEAT_FIRST; end
			else if (repeat_cnt == 24'd0) begin step = 1'b1; repeat_cnt <= REPEAT_NEXT; end
			else repeat_cnt <= repeat_cnt - 24'd1;

			if (step && key == 8'h00) begin
				if (up)    cur_row <= (cur_row == 0) ? 3'(ROWS - 1) : cur_row - 3'd1;
				if (down)  cur_row <= (cur_row == 3'(ROWS - 1)) ? 3'd0 : cur_row + 3'd1;
				if (left)  cur_col <= cur_col - 4'd1;   // 16 columns: wraps naturally
				if (right) cur_col <= cur_col + 4'd1;
			end

			// A: modifiers latch until the next key is released; other keys are held while A is
			if (btn_a & ~pad_d[4]) begin
				if (usage_is_mod) begin
					if (usage == 8'hE0) mods[0] <= ~mods[0];
					if (usage == 8'hE1 || usage == 8'hE5) mods[1] <= ~mods[1];
					if (usage == 8'hE2) mods[2] <= ~mods[2];
				end else
					key <= usage;
			end
			if (~btn_a & pad_d[4] & (key != 8'h00)) begin
				key <= 8'h00;
				mods <= 3'b000;
			end

			// B closes the keyboard
			if (btn_b & ~pad_d[5]) begin
				visible <= 1'b0;
				key <= 8'h00;
			end
		end
	end
end

endmodule


module osk_overlay #(
	parameter FONT_FILE = "core/osk_font.hex"
) (
	input  wire        clk,
	input  wire        visible,
	input  wire  [2:0] cur_row,
	input  wire  [3:0] cur_col,
	input  wire  [2:0] mods,
	input  wire        badge,        // show the pad-mode label
	input  wire  [2:0] badge_mode,   // 0 JOYSTICK, 1 MOUSE, 2 KEYS, 3 PORT 1, 4 PORT 2
	input  wire        loading,      // a file is being loaded: loading screen
	input  wire  [2:0] load_kind,    // 0 program, 1 cartridge, 2 disk, 3 tape, 4 ROM
	input  wire [11:0] load_pct,     // 3 BCD digits

	input  wire [23:0] in_rgb,
	input  wire        in_de,
	input  wire        in_skip,
	input  wire        in_hs,
	input  wire        in_vs,

	// same stream, 2 clocks later
	output reg  [23:0] video_rgb,
	output reg         video_de,
	output reg         video_skip,
	output reg         video_hs,
	output reg         video_vs
);

`include "osk_layout.svh"

localparam KB_W = 320, KB_H = 80, CELL_W = 20, CELL_H = 16;

reg [7:0] font[1024];
initial $readmemh(FONT_FILE, font);

// geometry of the incoming picture, measured from the previous line / frame
reg  [9:0] px, py, width, height;
reg        de_d;

always @(posedge clk) begin
	de_d <= in_de;
	if (in_de && !in_skip) px <= px + 10'd1;
	if (de_d && !in_de) begin
		width <= px;
		px <= 10'd0;
		py <= py + 10'd1;
	end
	if (in_vs) begin
		height <= py;
		py <= 10'd0;
	end
end

// stage 0: keyboard-relative position
wire [9:0]  kx = px - ((width - 10'(KB_W)) >> 1);
wire [9:0]  ky = py - (height - 10'(KB_H) - 10'd4);
wire        in_kb = visible && in_de && (kx < 10'(KB_W)) && (ky < 10'(KB_H)) && (width >= 10'(KB_W)) && (height > 10'(KB_H + 4));
// kx / 20 for kx < 320, exact over that range
wire [16:0] col_mul = kx * 17'd205;
wire [3:0]  col = col_mul[15:12];
wire [5:0]  cx = 6'(kx - col * 10'(CELL_W));
wire [2:0]  row = ky[6:4];
wire [3:0]  cy = ky[3:0];
// 2 label characters start 2 pixels into the cell; a single one is centred
wire [5:0]  tx0 = osk_narrow(row, col) ? 6'd6 : 6'd2;
wire [5:0]  tx = cx - tx0;
wire [3:0]  ty = cy - 4'd4;
wire        text_area = (cx >= tx0) && (cx < tx0 + (osk_narrow(row, col) ? 6'd8 : 6'd16)) && (cy >= 4'd4) && (cy < 4'd12);
wire [7:0]  cell_usage = osk_usage(row, col);
wire        latched = (cell_usage == 8'hE0 && mods[0]) || ((cell_usage == 8'hE1 || cell_usage == 8'hE5) && mods[1]) ||
                      (cell_usage == 8'hE2 && mods[2]);

// pad-mode label, top left: 8 characters at x 8-71, y 4-11 (keyboard is at the bottom)
wire [9:0]  bx = px - 10'd8;
wire [9:0]  by = py - 10'd4;
wire        in_badge = badge && in_de && (bx < 10'd64) && (by < 10'd8);
function automatic [6:0] badge_char(input [2:0] mode, input [2:0] pos);
	reg [63:0] s;
	case (mode)
		3'd1: s = " MOUSE  ";
		3'd2: s = "  KEYS  ";
		3'd3: s = " PORT 1 ";
		3'd4: s = " PORT 2 ";
		default: s = "JOYSTICK";
	endcase
	badge_char = s[(7 - pos) * 8 +: 7];
endfunction

// loading screen: "LOADING DISK 42%" in 2x text (16 chars, 256 px) centred, progress bar below
wire [9:0]  lx = px - ((width - 10'd256) >> 1);
wire [9:0]  ly = py - ((height >> 1) - 10'd16);
wire        load_text = loading && in_de && lx < 10'd256 && ly < 10'd16;
wire        load_bar  = loading && in_de && lx < 10'd256 && ly >= 10'd24 && ly < 10'd32;
wire [9:0]  bar_fill  = {6'd0, load_pct[11:8]} * 10'd100 + {6'd0, load_pct[7:4]} * 10'd10 + {6'd0, load_pct[3:0]};
function automatic [6:0] load_char(input [2:0] kind, input [11:0] pct, input [3:0] pos);
	reg [127:0] s;
	case (kind)
		3'd0: s = "LOADING PRG     ";
		3'd1: s = "LOADING CART    ";
		3'd2: s = "LOADING DISK    ";
		3'd3: s = "LOADING TAPE    ";
		default: s = "LOADING ROM     ";
	endcase
	case (pos)
		4'd12: load_char = pct[11:8] != 0 ? 7'd49 : 7'd32;                                  // hundreds
		4'd13: load_char = (pct[11:8] != 0 || pct[7:4] != 0) ? 7'd48 + {3'd0, pct[7:4]} : 7'd32;
		4'd14: load_char = 7'd48 + {3'd0, pct[3:0]};
		4'd15: load_char = 7'd37;                                                          // %
		default: load_char = s[(15 - pos) * 8 +: 7];
	endcase
endfunction

// stage 1: glyph row lookup
reg  [7:0]  glyph;
reg         loading_s1, ltext_s1, lbar_s1, lfill_s1;
reg  [2:0]  bit_s1;
reg         in_kb_s1, badge_s1, text_s1, edge_s1, cursor_s1, latched_s1;
reg [23:0]  rgb_s1;
reg         de_s1, skip_s1, hs_s1, vs_s1;

always @(posedge clk) begin
	glyph      <= load_text ? font[{load_char(load_kind, load_pct, lx[7:4]), ly[3:1]}] :
	              in_badge  ? font[{badge_char(badge_mode, bx[5:3]), by[2:0]}]
	                        : font[{osk_char(row, col, tx[3]), ty[2:0]}];
	bit_s1     <= load_text ? lx[3:1] : in_badge ? bx[2:0] : tx[2:0];
	loading_s1 <= loading;
	ltext_s1   <= load_text;
	lbar_s1    <= load_bar;
	lfill_s1   <= {6'd0, lx} < (({6'd0, bar_fill} * 16'd41) >> 4);   // pct * 2.56 px
	in_kb_s1   <= in_kb | in_badge;
	badge_s1   <= in_badge;
	text_s1    <= text_area;
	edge_s1    <= (cx == 6'd0) || (cy == 4'd0) || (cx == 6'(CELL_W - 1));
	cursor_s1  <= (row == cur_row) && (col == cur_col);
	latched_s1 <= latched;
	{rgb_s1, de_s1, skip_s1, hs_s1, vs_s1} <= {in_rgb, in_de, in_skip, in_hs, in_vs};
end

// stage 2: compose
always @(posedge clk) begin
	reg ink;
	ink = text_s1 && glyph[bit_s1];
	{video_de, video_skip, video_hs, video_vs} <= {de_s1, skip_s1, hs_s1, vs_s1};
	if (loading_s1 && de_s1)
		video_rgb <= ltext_s1 ? (glyph[bit_s1] ? 24'hFFFFFF : 24'h40318D) :     // C64 blue on light blue
		             lbar_s1  ? (lfill_s1 ? 24'h7869C4 : 24'h2B2160) : 24'h40318D;
	else if (!in_kb_s1) video_rgb <= rgb_s1;
	else if (badge_s1)  video_rgb <= glyph[bit_s1] ? 24'hFFFFFF : 24'h203060;
	else if (edge_s1)   video_rgb <= 24'h181820;
	else if (cursor_s1) video_rgb <= ink ? 24'h000000 : 24'hF0F0F0;
	else if (latched_s1) video_rgb <= ink ? 24'h000000 : 24'hE0A000;
	else                video_rgb <= ink ? 24'hFFFFFF : 24'h505868;
end

endmodule

`default_nettype wire
